### ISSUE TITLE
upgrade GuzzleHttp

### ISSUE THREAD

**Issue by patoulich** [SDV-Plurimedia/ibp-sdk-php#11]
Le package "guzzlehttp/guzzle" 6.x présente un problème au niveau de "GuzzleException" pour les utilisateurs de PhpStorm :
Cette classe est définit 2 fois dans le même fichier PHP pour être compatible avec des version PHP 5.x.

![phpstorm_guzzleexception](https://user-images.githubusercontent.com/3824455/153154528-161c7cc6-e09a-416c-9b33-284b99754244.png)

Lorsque, dans mes projets, je souhaite utiliser GuzzleHttp v7.x, je suis bloqué et je ne peux pas upgrader car votre paquet bloque la version à "^6.2" :
https://github.com/SDV-Plurimedia/ibp-sdk-php/blob/master/composer.json#L14

Pouvez-vous autoriser, en plus, la version "^7.0" de cette façon ?

```"guzzlehttp/guzzle": "^6.2" || "^7.0"```

**Comment by louisjj** [comment]
Bonjour,

Une version `1.8` du package est disponible avec le support de guzzle 7

**Comment by patoulich** [comment]
c'est parfait, merci.
