### ISSUE TITLE
Bug sur la gestion d'erreur

### ISSUE THREAD

**Issue by patrick-ldi** [SDV-Plurimedia/ibp-sdk-php#13]
Lors de l'utilisation de ce SDK pour envoyer dans IBP, nous rencontrons de temps en temps l'erreur suivante : 

```
Argument 1 passed to SdV\Ibp\Client::toError() must be of the type array, null given, called in vendor/sdv/ibp-sdk-php/src/MakesHttpRequests.php on line 162
```

**Comment by fabriceclementz** [comment]
Bonjour @patrick-ldi 
Ce bug a été corrigé sur la version 1.8.1 https://packagist.org/packages/sdv/ibp-sdk-php#1.8.1

Une `ApiException` indiquant qu'il ne s'agit pas d'un JSON valide est désormais levée.

**Comment by patrick-ldi** [comment]
ok merci.
