### ISSUE TITLE
[DEPRECATED][PHP8.2] Creation of dynamic property is deprecated

### ISSUE THREAD

**Issue by patrick-ldi** [SDV-Plurimedia/ibp-sdk-php#14]
# Problème
Lors de l'utilisation de la méthode file() d'un "IBPClient", nous avons les erreurs "deprecated" suivantes qui apparaissent depuis le passage en PHP 8.2 : 

```
[php] Deprecated: Creation of dynamic property SdV\Ibp\Resources\File::$focal is deprecated
[php] Deprecated: Creation of dynamic property SdV\Ibp\Resources\File::$focal is deprecated

```

La ligne en cause est la suivante : 
https://github.com/SDV-Plurimedia/ibp-sdk-php/blob/6fdfc6db4522b3c8bf6576a2e3ae340216e3afe3/src/Resources/Resource.php#L32

# Comment reproduire ce bug

- être sur PHP 8.2
- appeler n'importe quelle méthode qui instancie l'objet "Resource", tel que "File" par exemple via ce code :
```
$file = $ibp->TagFile('59142cd4a64da6014c769813', 'manual', ['tag 1', 'tag 2']);
```
ou encore
```
$file = $ibp->file('59142cd4a64da6014c769813');
```

# Solution proposée : 
Ajouter l'attribut : #[\AllowDynamicProperties]
voir classe d'origine : https://github.com/laravel/forge-sdk/blob/3.x/src/Resources/Resource.php

**Comment by flibidi67** [comment]
Salut Patrick,

Le correctif que tu as suggéré est dispo sur le tag **1.8.4**. N'hésite pas à proposer une pull request si tu rencontres un autre souci de ce genre ;)

Bonne journée,
jp

**Comment by patrick-ldi** [comment]
parfait, merci 👍
